AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create S3 bucket with versioning enabled

Resources:
  IntelliPaatS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: intellipaat-anubhav
      VersioningConfiguration:
        Status: Enabled